services:
  - type: web
    name: youtube-ai-analyzer
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: export PATH="$PATH:/opt/render/project/src/.render/ffmpeg"; gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_DEBUG
        value: "false"
      - key: GEMINI_API_KEY
        sync: false